@startuml

abstract class Persona{
    - nombre : String
    - apellido : String
}

class Empleado extends Persona {
    - nroLegajo : int

}

class Visitante extends Persona {
    - dni : int
    - presente : boolean
    - habitacion : int
    - gastos : float
    - domicilioOrigen : String
    - origen : String


}

class Habitacion {
    - tipoHabitacion : String
    - numero : int
    - coste : int
    - disponible : boolean
}

class Estadia extends Reserva{
     - checkIn : boolean
     - checkOut : boolean
     - costo : int
}

class Reserva {
     # visitante : Visitante
     # habitacion : Habitacion
     # llegada : Date
     # salida : Date

}

interface administrarReserva {
    crearReserva(Reserva reserva) : void
    editarReserva(Reserva reserva) : void
    eliminarReserva(Reserva reserva) : void
    listarReservas : void
}







@enduml